version: "3.7"
  
services:
  # Infrastructure Services
  nginx:
    container_name: nginx
    build: 
      context: ./docker/images/nginx
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USERID: ${USER_ID}
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./docker/images/nginx/config/sites:/etc/nginx/conf.d
      - ${PROJECTS_PATH}:/app/web/notifications
    networks:
      - app-network
    depends_on:
      - notifications

  database:
    container_name: database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cintelink
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - app-network
    ports:
      - ${DB_PORT_APP}:3306
    volumes:
     - app_mysql:/var/lib/mysql

  notifications:
    container_name: notifications
    build: 
      context: ./docker/images/notifications
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USERID: ${USER_ID}
    restart: always
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
       # php config vars
      PHP_DISPLAY_ERRORS: 1
      PHP_MEMORY_LIMIT: 2048M
      PHP_MAX_EXECUTION_TIME: -1
      PHP_EXTENSION_DEBUG: 1
      PHP_SESSION_GC_MAXLIFETIME: 36000000
      PHP_SESSION_GC_PROBABILITY: 0
      PHP_SESSION_COOKIE_LIFETIME: 0
      FPM_PROCESS_IDLE_TIMEOUT: 1800
      FPM_REQUEST_TERMINATE_TIMEOUT: 1800
      XDEBUG_PORT: 9003
      XDEBUG_KEY: docker
    volumes:
      - ${NOTIFICATIONS_PATH_APP}:/app/web/notifications
      - ./docker/images/notifications/config/fpm.conf:/usr/local/etc/php-fpm.d/www.conf

volumes:
  app_mysql: null

networks:
  app-network:
    driver: bridge